name: shut
version: 0.15.1
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
license: MIT
url: https://github.com/NiklasRosenstein/shut
description: Automates the heavy lifting of release and distribution management for
  pure Python packages.
typed: true
requirements:
- python ^3.6
- beautifulsoup4 ^4.8.1
- databind.core ^0.4.0
- databind.json ^0.4.0
- click ^7.0
- jinja2 ^2.11.1
- networkx ^2.4
- nr.fs ^1.5.0
- nr.parsing.date ^0.4.0
- nr.proxy ^1.0.0
- nr.pylang.utils ^0.0.1
- nr.utils.git ~0.1.3
- nr.stream ~0.0.4
- requests ^2.22.0
- packaging ^20.1
- PyYAML ^5.1.0
- termcolor ^1.1.0
- twine
- wheel
test-requirements:
- pytest
entrypoints:
  console_scripts:
  - shut = shut.commands:shut
package-data:
  - include: data/license_templates/*.txt
test-driver:
  type: pytest
